name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --target compiler

    - name: Tests
      run: |
        chmod +x tests/ifcc-wrapper.sh
        python3 tests/ifcc-test.py tests/testfiles/

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "ifcc-test-output/test_report.xml"
      
    - name: Publish Tests Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ifcc-test-output
        path: ifcc-test-output/*